#!/usr/bin/env python
# encoding: utf-8

import cetacean
from subprocess import check_call

version = cetacean.__version__
version_tag = "v{0}".format(version)

check_call(['git', 'tag', version_tag])
check_call(['git', 'push'])

try:
    check_call(['git', 'push', '--tags'])
except Exception as e:
    check_call(['git', 'tag', '-d', version_tag])
    raise e

try:
    check_call(['python', 'setup.py', 'sdist', 'upload'])
except Exception as e:
    check_call(['git', 'push', 'origin', ':{0}'.format(version_tag)])
    check_call(['git', 'tag', '-d', version_tag])
    raise e
