#!/usr/bin/env python
# encoding: utf-8

import cetacean
from subprocess import check_call

version = cetacean.__version__

check_call(['git', 'tag', version])
check_call(['git', 'push', '--tags'])
check_call(['python', 'setup.py', 'sdist', 'upload'])
